apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulk-send
  namespace: 
  labels:
    app.kubernetes.io/name: bulk-send
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bulk-send
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bulk-send
    spec:
      containers:
      - name: hn-bulksend
        image: trieve/hn-bulksend:check
        imagePullPolicy: Always
        env:
          - name: REDIS_URL
            value: "<redis-uri>"
          - name: API_KEY
            value: "<insert-key>"
          - name: DATASET_ID
            value: "<dataset-id>"
          - name: API_BASE_URL
            value: "https://hackernews.withtrieve.com/api"
