apiVersion: apps/v1
kind: Deployment
metadata:
  name: set-ids
  namespace: 
  labels:
    app.kubernetes.io/name: set-ids
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: set-ids
  template:
    metadata:
      labels:
        app.kubernetes.io/name: set-ids
    spec:
      containers:
      - name: hn-setids
        image: trieve/hn-setids
        imagePullPolicy: Always
        env:
          - name: REDIS_URL
            value: <redis-uri>
